### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by tgivslife** [swissonid/android-design-support-lib-sample#11]
Hi,

Tested the sample on a nexus 5. How to reproduce the crash:
- open the app
- hit back button, app closes
- open app again and crash 

Process: ch.swissonid.design_samples, PID: 5637
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.swissonid.design_samples/ch.swissonid.design_lib_sample.DrawerActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
            at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
            at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
            at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
            at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
            at ch.swissonid.design_lib_sample.util.Navigator.replaceFragment(Navigator.java:102)
            at ch.swissonid.design_lib_sample.util.Navigator.setRootFragment(Navigator.java:91)
            at ch.swissonid.design_lib_sample.DrawerActivity.setNewRootFragment(DrawerActivity.java:69)
            at ch.swissonid.design_lib_sample.DrawerActivity.onCreate(DrawerActivity.java:53)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke

**Comment by swissonid** [comment]
Thx for reporting
