### ISSUE TITLE
app won't run on API 19

### ISSUE THREAD

**Issue by macarthor** [swissonid/android-design-support-lib-sample#18]
hi all,

i run this STOCK app without any modification, on an android 4.4 mobile, but fails. LOGCAT shows:

`Process: ch.swissonid.design_samples, PID: 18966
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.swissonid.design_samples/ch.swissonid.design_lib_sample.DrawerActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.design.widget.NavigationView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
            at android.app.ActivityThread.access$900(ActivityThread.java:164)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5377)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.design.widget.NavigationView
            at android.view.LayoutInflater.createView(LayoutInflater.java:626)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at ch.swissonid.design_lib_sample.DrawerActivity.onCreate(DrawerActivity.java:41)
            at android.app.Activity.performCreate(Activity.java:5433)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
            at android.app.ActivityThread.access$900(ActivityThread.java:164)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5377)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at ch.swissonid.design_lib_sample.DrawerActivity.onCreate(DrawerActivity.java:41)
            at android.app.Activity.performCreate(Activity.java:5433)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
            at android.app.ActivityThread.access$900(ActivityThread.java:164)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5377)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
            at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:464)
            at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6371)
            at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java:1225)
            at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1062)
            at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:82)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:768)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:184)
            at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:227)
            at android.support.design.widget.NavigationView.<init>(NavigationView.java:152)
            at android.support.design.widget.NavigationView.<init>(NavigationView.java:88)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at ch.swissonid.design_lib_sample.DrawerActivity.onCreate(DrawerActivity.java:41)
            at android.app.Activity.performCreate(Activity.java:5433)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
            at android.app.ActivityThread.access$900(ActivityThread.java:164)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5377)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)`

this app runs well on an android 5.0 mobile. but design lib is for android 2.1 and above?

any hints?

**Comment by macarthor** [comment]
i've got it:
in `drawer_header.xml`, `CircleImageView` does not support `layout_margin*` attributes in 4.4.

**Comment by swissonid** [comment]
Thx now it should run...But looks very ugly. I hope the find some time today to fix it.

**Comment by macarthor** [comment]
@swissonid may you could try layout_marginLeft/Right instead of start/end.

**Comment by macarthor** [comment]
@swissonid another problem, this sample runs on 4.4.2, but get none titlebar background...

**Comment by swissonid** [comment]
That should  be already fixed. Have you updated to the newest version?

**Comment by luisfernandezbr** [comment]
Solution from @neerajgoel
Copy all xml drawables from "drawable-v21" folder to "drawable".
